# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmMNv2RuDBKFr0K8Lq6J7siMd_suxseq
"""

!pip install -r requirements.txt